// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"
	"time"
)

type Meet struct {
	ID          string         `json:"id"`
	Title       sql.NullString `json:"title"`
	Description sql.NullString `json:"description"`
	Recording   sql.NullString `json:"recording"`
	Author      string         `json:"author"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type User struct {
	ID                int32          `json:"id"`
	Username          string         `json:"username"`
	FirstName         string         `json:"first_name"`
	LastName          string         `json:"last_name"`
	MiddleName        sql.NullString `json:"middle_name"`
	Email             string         `json:"email"`
	HashedPassword    string         `json:"hashed_password"`
	Quote             sql.NullString `json:"quote"`
	Bio               sql.NullString `json:"bio"`
	DateOfBirth       time.Time      `json:"date_of_birth"`
	Avatar            string         `json:"avatar"`
	Banner            sql.NullString `json:"banner"`
	ProfileComplete   bool           `json:"profile_complete"`
	PasswordChangedAt time.Time      `json:"password_changed_at"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
}
